config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/home', to: 'pages#home'

  resources :artists do
    resources :tracks
  end

  resources :wordclouds
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :tracks, dependent: :destroy

  scope :by_name, -> { order :name}

  def to_s
    name
  end
end

app/models/chart.rb
class Chart < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :entries

  scope :by_name, -> { order :name }

  # Pass in an array of entries of the form
  # ['artist name', 'track name']
  # to create the chart entries
  def create_chart_entries chart_entries
    chart_entries.each_with_index do |entry, index|
      artist = Artist.find_or_create_by name: entry[0]
      track = artist.tracks.find_or_create_by title: entry[1]
      entries.create! track: track, position: index+1
    end
  end
#  TODO What about duplicate artist names?
#  TODO What about duplicate track titles?

  def to_s
    name
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :chart
  belongs_to :track

  def to_s
    "#{position}. #{track}"
  end
end

app/models/track.rb
class Track < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :artist

  scope :by_title, -> { order :title }

  def to_s
    "#{artist} — #{title}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  layout 'page'
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, except: :index

  def index
    @artists = Artist.by_name
  end

  def show
    @tracks = @artist.tracks.by_title
  end

  private
  def set_artist
    @artist = Artist.friendly.find params[:id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @charts = Chart.all.by_name.includes(entries: {track: :artist})
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_artist
  before_action :set_track, except: :index

  def show
  end

  private
  def set_artist
    @artist = Artist.friendly.find params[:artist_id]
  end

  def set_track
    @track = @artist.tracks.friendly.find params[:id]
  end
end

app/controllers/wordclouds_controller.rb
class WordcloudsController < ApplicationController
  before_action :set_chart, except: :index

  def index
    @chart = Chart.find_by_name '1970s'
  end

  def show
    words = Hash.new 0

    @chart.entries.includes(:track).map(&:track).each do |track|
      if track.lyrics
        track.lyrics.
            downcase.
            strip.
            gsub(/\s+/m, ' ').
            gsub(/[^a-z0-9 ]/, '').
            split(' ').
            each{|word| words[word] += 1}
      end
    end

    render json: words.
        select{|word, count| word.length > 4 && count > 3 && !STOPWORDS.include?(word)}.
        map{|word, count| {text: word, value: (Math.log(count) * 10).round}}
  end

  private
  def set_chart
    @chart = Chart.find_by_name! params[:id]
  end

  STOPWORDS = Set.new(%w[
      and the with its all  cause didnt where
      youll youre youve
      there theyll those theyre could
])
end

app/helpers/application_helper.rb
module ApplicationHelper
  def main_logo
    link_to image_tag(t('site.logo.header.large'), alt: t('site.logo.header.alt')), home_path
  end

  def current_version
    Rails.application.config.deployed_at.as_json
  end
end

app/helpers/cookies_helper.rb
# frozen_string_literal: true
module CookiesHelper
  def show_cookie_banner?

    # ! cookies_accepted?
  end

  def cookies_accepted?
    request.cookies['cookie']
  end

  def analytics_cookies_ok?
    request.cookies['cookie'] != 'no_analytics'
  end
end

app/helpers/page_helper.rb
# frozen_string_literal: true
module PageHelper
  def configure_page options
    @page_options = options
  end

  def page_options
    @page_options ||= {}
  end

  def page_title
    site = page_options[:site_title] || t('site.title')
    title = page_options[:title]

    if title.blank?
      site
    else
      page_title_format site, title
    end
  end

  def page_title_format site, title
    "#{title} | #{site}"
  end

  def page_description
    description = page_options[:description]
    if description.blank?
      t('site.description')
    else
      description
    end
  end

  def canonical_url
    cleaned_url(page_options[:canonical_url] || request.url)
  end

  def open_graph_image
    page_options[:open_graph_image] || "/#{t('site.logo.open_graph')}"
  end

  def page_no_index?
    page_options[:noindex]
  end

  def copyright_message
    t('site.copyright_message', year: Time.now.year)
  end

  def last_deployment_timestamp
    t('site.last_deployment_timestamp', time: last_deployed_at)
  end

  def cleaned_url url
    url.split('?').first.sub(/\/$/, '')
  end

  def last_deployed_at
    Rails.application.config.deployed_at if admin?
  end
end

app/views/artists/index.html.haml
- configure_page title: t('artists.index.title')

.artists.index.page
  %h2 Artists
  %table.artists-list
    %thead
      %tr
        %th Artist
    %tbody
      - @artists.each do |artist|
        %tr.artist
          %td.name= link_to artist.name, artist

app/views/artists/show.html.haml
- configure_page title: @artist.name

.artist.show.page
  %h2.title= @artist

  %section
    %table.track-list
      %thead
        %tr
          %th Tracks
          %th Lyrics
      %tbody
        - @tracks.each do |track|
          %tr.track
            %td.title= link_to track.title, [@artist, track]
            %td.check= track.lyrics.present? ? '✓' : ''

app/views/layouts/application.html.haml
!!!
%html{lang: 'en'}
  %head= render 'shared/head'
  %body
    = render 'shared/flash-messages'
    = content_for?(:body) ? content_for(:body) : yield
    = render 'shared/analytics'
    = render 'shared/cookie_banner'

app/views/layouts/page-with-sidebar.html.haml
- content_for :body do
  #page
    = render 'shared/header'
    #main.with-sidebar
      = render 'shared/sidebar'
      #content= yield
      #footer= render 'shared/footer'
  = render 'shared/scripts'

= render template: 'layouts/application'

app/views/layouts/page.html.haml
- content_for :body do
  #page
    = render 'shared/header'
    #main
      #content= yield
      #footer= render 'shared/footer'
  = render 'shared/scripts'

= render template: 'layouts/application'

app/views/pages/home.html.haml
.home.page
  %h1.title= t('site.name')
  %h2.tagline= t('site.tagline')

  - @charts.each do |chart|
    %section.decade
      %h3= chart.name
      -#%p.artists
         = chart.entries.map(&:track).map(&:artist).map(&:name).uniq.sort.join(', ')
      .react-wordcloud{ data: { url: "/wordclouds/#{chart.name}.json" }}

app/views/shared/_analytics.html.haml
- if analytics_cookies_ok?
  %script{async:"", src: "https://www.googletagmanager.com/gtag/js?id=#{Rails.application.config.google_analytics_id}"}

  :javascript
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date())
    gtag('config', "#{Rails.application.config.google_analytics_id}", {anonymize_ip: true})

app/views/shared/_cookie_banner.html.haml
- if show_cookie_banner?
  #cookie-banner.cookie-banner
    .actions
      = link_to 'Cookie Settings', cookies_path, class: 'button clear'
      = link_to 'Accept Cookies',  cookies_path, class: 'button primary', method: :post, remote: true
    .text
      We use cookies and third party services to enhance our website's functionality, to analyse our traffic and to provide a better experience for our visitors.
      = link_to 'You can read our cookie policy here.', cookies_path

app/views/shared/_flash-messages.html.haml
.flash-messages
  - [:notice, :error, :alert].each do |level|
    - unless flash[level].blank?
      .alert{class: level}= flash[level]

app/views/shared/_footer.html.haml
#footer.footer
  .site-menu
    %ul
      %li.title Company
      %li= link_to 'Home', home_path
      %li= link_to 'Artists', artists_path
      -#%li= link_to 'Privacy', privacy_path
      -#%li= link_to 'Cookies', cookies_path
      -#%li= link_to 'Contact Us', contacts_path


  .sub-footer
    .copyright= copyright_message
    -#.creative-commons-notice
    -#  = link_to 'Several images are licensed under Creative Commons.', creative_commons_path

app/views/shared/_head.html.haml
%title= page_title
%meta{name: 'description', content: page_description}

= csrf_meta_tags
= csp_meta_tag

%link{rel: 'canonical', href: canonical_url}
%link{rel: 'icon', href: '/favicon.png', sizes: '180x180', type: 'image/png'}
%link{rel: 'apple-touch-icon', href: '/apple-touch-icon-precomposed.png', sizes: '180x180', type: 'image/png'}

%meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
%meta{'http-equiv': 'Content-Type', content: 'text/html;charset=utf-8'}
%meta{'http-equiv': 'X-UA-Compatible', content: 'IE=edge,chrome=1'}
%meta{name: 'analytics_id', content: Rails.application.config.google_analytics_id}

= render 'shared/head/open_graph'
= render 'shared/head/fonts'

= stylesheet_link_tag 'application', media: 'all'

app/views/shared/_header.html.haml
#header.header
  .logo= link_to main_logo, root_path

  %ul.top-menu
    %li= link_to 'artists', artists_path

app/views/shared/_scripts.html.haml
-## Only include this on non-react pages
= javascript_pack_tag 'wordcloud'

app/views/shared/_sidebar.html.haml
#sidebar.sidebar

app/views/shared/head/_fonts.html.haml
-#%link{ href:'https://fonts.googleapis.com/css?family=Noto+Serif:400,400i,700,700i&display=swap', rel:'stylesheet' }

app/views/shared/head/_open_graph.html.haml
%meta{name: 'og:title', content: page_title}
%meta{name: 'og:description', content: page_description}
%meta{name: 'og:url', content: canonical_url}
%meta{name: 'og:image', content: open_graph_image}

%meta{name: 'twitter:title', content: page_title}
%meta{name: 'twitter:description', content: page_description}
%meta{name: 'twitter:url', content: canonical_url}
%meta{name: 'twitter:image', content: open_graph_image}

app/views/tracks/show.html.haml
- configure_page title: @track.to_s

.track.show.page
  %h2.title= @track.title
  %h3.subtitle= @artist.name

  %section
    %h4 Lyrics
    - if @track.lyrics.present?
      .lyrics= @track.lyrics
    - else
      .no-lyrics No lyrics available

app/views/wordclouds/index.html.haml
.wordclouds.index.page
  %h1.title= t('site.name')
  %h2.tagline= t('site.tagline')

  %section.decade
    %h3= @chart.name
    .react-wordcloud{ data: { url: "/wordclouds/#{@chart.name}.json" }}